module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        // root: ['./src'],
        root: ['.'],
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.json',
          '.png',
        ],
        alias: {
          '@util': './src/util',
          '@styles': './src/styles',
          '@components': './src/components',
          '@dashboard': './src/features/dashboard',
          '@features': './src/features',
          '@flow': './src/flow',
          '@images': './assets/images',
          '@icons': './assets/icons',
          '@navigation': './src/navigation',
          '@api': './src/util/api',
          '@app': './src/app',
          '@config': './src/config',
          '@palette': './node_modules/@simplehabitapp/nocturne-palette/static/styles.scss',
          '@sdui': ['./src/util/SDUI'],
          '@sdui-dataLayer': ['./src/util/SDUI/dataLayer/core'],
          '@sdui-viewModels': ['./src/util/SDUI/containerViewModels'],
          assets: './assets',
          '@taskManager': './src/taskManager',
        },
      },
    ],
  ],
};
